### ISSUE TITLE
log issue

### ISSUE THREAD

**Issue by simonweiler** [brainglobe/cellfinder-visualize#48]
**Describe the bug**
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
'C:\\Users\\sweiler\\.brainrender\\log.log'

**To Reproduce**
run cellfinder _visualize, gui appaers, set your grouos etc, only tick box use brainrender and press run

**Expected behaviour**
brainredner scene opens and dsiplays reference frame + cells

**Log file**
[NA]

**Screenshots**
![image](https://user-images.githubusercontent.com/15692611/222466539-12002550-36f4-4f2f-869a-a185febe12a8.png)

**Computer used (please complete the following information):**

- OS: Windows 10 python 10
- Version python 10
- Hardware specs [
![image](https://user-images.githubusercontent.com/15692611/222466872-1061a18d-6d21-4a41-938b-9d7ed0e6b873.png)
]

**Additional context**

**Comment by stephenlenzi** [comment]
This seems to be a windows issue resulting from calling brainrender in a process
